import { Model } from './types';

export const MOCK_MODELS: Model[] = [
  {
    id: 'm1',
    username: 'sophia_latina',
    displayName: 'Sophia Latina',
    age: 22,
    country: 'Colombia',
    countryCode: 'CO',
    gender: 'female',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    viewersCount: 2840,
    rating: 4.9,
    favoriteCount: 18400,
    rank: 1,
    topic: '🔥 [META DE HOY: 850/1000] Baile sensual en lencería roja | Toy Lovense Activo ⚡',
    goalTitle: 'Baile de la victoria + Show sin censura',
    goalCurrent: 850,
    goalTarget: 1000,
    tags: ['Latina', 'Petite', 'Lovense', 'HD 1080p', 'Bailarina', 'Curved'],
    languages: ['Español', 'Inglés'],
    ethnicity: 'Hispana/Latina',
    bodyType: 'Delgada con curvas',
    hairColor: 'Castaño oscuro',
    tokensPerMin: 60,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Hola mis amores! Soy Sophia de Medellín. Me encanta bailar, interactuar en el chat y pasar un tiempo inolvidable contigo. ¡El juguete Lovense reacciona a cada propina!',
    schedule: 'Lunes a Viernes: 18:00 - 02:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Flash de Pecho', tokens: 25, description: 'Flash rápido de 5 segundos', actionType: 'flash' },
      { id: 't2', label: 'Baile Sensual', tokens: 50, description: 'Baile de 1 minuto con tu canción', actionType: 'dance' },
      { id: 't3', label: 'Lovense Max Vibration', tokens: 100, description: 'Vibración nivel 10 por 30 segundos', actionType: 'lovense' },
      { id: 't4', label: 'Quitar Top', tokens: 200, description: 'Quita prenda superior en vivo', actionType: 'strip' },
      { id: 't5', label: 'Privado de 5 Minutos', tokens: 300, description: 'Acceso directo a show VIP', actionType: 'custom' },
    ],
    chatUrl: 'https://stripcash.com/live/sophia_latina',
    affiliateUrl: 'https://stripcash.com/api/models/sophia_latina?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/sophia_latina'
  },
  {
    id: 'm2',
    username: 'isabella_sweet',
    displayName: 'Isabella & Alex',
    age: 25,
    country: 'España',
    countryCode: 'ES',
    gender: 'couple',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    viewersCount: 1920,
    rating: 4.8,
    favoriteCount: 12100,
    rank: 2,
    topic: '💖 PAREJA EN VIVO | Probando nuevos juguetes interactivos | Meta: 1200 Tokens 🔥',
    goalTitle: 'Show intenso en pareja',
    goalCurrent: 910,
    goalTarget: 1200,
    tags: ['Pareja', 'Lovense', 'HD 1080p', 'Tatuajes', 'VR Cams', 'Español'],
    languages: ['Español', 'Portugués'],
    ethnicity: 'Caucásica',
    bodyType: 'Atléticos',
    hairColor: 'Rubio / Moreno',
    tokensPerMin: 90,
    isHd: true,
    isVr: true,
    isLovense: true,
    bio: 'Somos una pareja real de Madrid buscando diversión, fantasías y conexión directa con nuestros espectadores. ¡Aceptamos sugerencias en chat!',
    schedule: 'Martes, Jueves y Sábados: 20:00 - 04:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Beso Apasionado', tokens: 20, description: 'Beso continuo de 15 segundos', actionType: 'custom' },
      { id: 't2', label: 'Lovense Doble Nivel 10', tokens: 75, description: 'Ambos juguetes vibran al máximo', actionType: 'lovense' },
      { id: 't3', label: 'Masaje Sensual', tokens: 150, description: 'Masaje con aceite perfumado', actionType: 'dance' },
      { id: 't4', label: 'Show Pareja VIP', tokens: 450, description: 'Show privado exclusivo', actionType: 'strip' }
    ],
    chatUrl: 'https://stripcash.com/live/isabella_sweet',
    affiliateUrl: 'https://stripcash.com/api/models/isabella_sweet?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/isabella_sweet'
  },
  {
    id: 'm3',
    username: 'camila_fit',
    displayName: 'Camila Rose',
    age: 21,
    country: 'México',
    countryCode: 'MX',
    gender: 'female',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    viewersCount: 1430,
    rating: 4.9,
    favoriteCount: 9500,
    rank: 3,
    topic: '👑 Cosplay de Gatita Neko | Chat interactivo y complaciendo peticiones 💕',
    goalTitle: 'Traje secreto de Cosplay',
    goalCurrent: 320,
    goalTarget: 600,
    tags: ['Cosplay', 'Latina', 'Petite', 'Lovense', 'Piercing', 'Joven'],
    languages: ['Español'],
    ethnicity: 'Hispana',
    bodyType: 'Petite / Delgada',
    hairColor: 'Negro',
    tokensPerMin: 50,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Fanática del anime, la música pop y los videojuegos. Me encanta disfrazarme y pasar momentos súper tiernos y picantes en transmisión.',
    schedule: 'Todos los días: 21:00 - 05:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Maullido de Gatita', tokens: 10, description: 'Sonido tierno personalizado', actionType: 'custom' },
      { id: 't2', label: 'Guiño + Beso Volado', tokens: 15, description: 'Con dedicación al usuario', actionType: 'custom' },
      { id: 't3', label: 'Lovense Onda 20s', tokens: 60, description: 'Vibración progresiva', actionType: 'lovense' },
      { id: 't4', label: 'Baile K-Pop', tokens: 120, description: 'Baile coreografiado en vivo', actionType: 'dance' }
    ],
    chatUrl: 'https://stripcash.com/live/camila_fit',
    affiliateUrl: 'https://stripcash.com/api/models/camila_fit?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/camila_fit'
  },
  {
    id: 'm4',
    username: 'victoria_queen',
    displayName: 'Victoria Trans',
    age: 24,
    country: 'Brasil',
    countryCode: 'BR',
    gender: 'trans',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyflights.mp4',
    viewersCount: 3100,
    rating: 5.0,
    favoriteCount: 24000,
    rank: 4,
    topic: '💎 QUEEN OF BRASIL | Trans Show Sin Censura | Lovense Max Vibrations ⚡',
    goalTitle: 'Aceite corporal + Show Privado',
    goalCurrent: 1400,
    goalTarget: 1500,
    tags: ['Trans', 'Latina', 'Lovense', 'Curved', 'Tatuajes', 'HD 1080p'],
    languages: ['Portugués', 'Español', 'Inglés'],
    ethnicity: 'Latina',
    bodyType: 'Curvilínea',
    hairColor: 'Rubio platino',
    tokensPerMin: 80,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Reina trans brasilera. Glamour, seducción, energía vibrante y el mejor ambiente interactivo de toda la plataforma.',
    schedule: 'Miércoles a Domingo: 22:00 - 06:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Saludo en Portugués', tokens: 20, description: 'Te llamo por tu nombre', actionType: 'custom' },
      { id: 't2', label: 'Lovense Turbo 45s', tokens: 100, description: 'Vibración de alta intensidad', actionType: 'lovense' },
      { id: 't3', label: 'Samba Sensual', tokens: 180, description: 'Baile tradicional brasilero', actionType: 'dance' },
      { id: 't4', label: 'Desnudo Completo', tokens: 350, description: 'Revelación total en cámara', actionType: 'strip' }
    ],
    chatUrl: 'https://stripcash.com/live/victoria_queen',
    affiliateUrl: 'https://stripcash.com/api/models/victoria_queen?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/victoria_queen'
  },
  {
    id: 'm5',
    username: 'lucas_hunk',
    displayName: 'Lucas Vance',
    age: 26,
    country: 'Argentina',
    countryCode: 'AR',
    gender: 'male',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    viewersCount: 880,
    rating: 4.7,
    favoriteCount: 6300,
    rank: 5,
    topic: '💪 Entrenamiento en vivo + Charla privada y peticiones del chat 🔥',
    goalTitle: 'Quitar camiseta de gimnasio',
    goalCurrent: 250,
    goalTarget: 400,
    tags: ['Hombres', 'Musculoso', 'Fitness', 'Español', 'Tatuajes'],
    languages: ['Español', 'Inglés'],
    ethnicity: 'Latino',
    bodyType: 'Atleta / Musculoso',
    hairColor: 'Castaño',
    tokensPerMin: 45,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Instructor de fitness de Buenos Aires. Amante de la buena conversación, el deporte y complacer fantasías masculinas y femeninas.',
    schedule: 'Lunes a Sábado: 16:00 - 00:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Flexión de Bíceps', tokens: 15, description: 'Demostración de fuerza', actionType: 'custom' },
      { id: 't2', label: 'Mostrar Abdominales', tokens: 40, description: 'Muestra abdomen marcado', actionType: 'flash' },
      { id: 't3', label: 'Show Privado Individual', tokens: 250, description: 'Charla VIP 1 a 1', actionType: 'custom' }
    ],
    chatUrl: 'https://stripcash.com/live/lucas_hunk',
    affiliateUrl: 'https://stripcash.com/api/models/lucas_hunk?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/lucas_hunk'
  },
  {
    id: 'm6',
    username: 'elena_milf',
    displayName: 'Elena Seduction',
    age: 38,
    country: 'Italia',
    countryCode: 'IT',
    gender: 'female',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    viewersCount: 2210,
    rating: 4.9,
    favoriteCount: 15600,
    rank: 6,
    topic: '🍷 Elegancia y seducción madura | Copa de vino + Lovense Interactivo',
    goalTitle: 'Aceitado de piernas y lencería',
    goalCurrent: 670,
    goalTarget: 800,
    tags: ['MILF', 'Elegante', 'Lovense', 'HD 1080p', 'Rubia', 'Caucásica'],
    languages: ['Italiano', 'Español', 'Inglés'],
    ethnicity: 'Caucásica',
    bodyType: 'Curvilínea / Madura',
    hairColor: 'Rubio dorado',
    tokensPerMin: 70,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Madura sofisticada de Milán. Experiencia, sensualidad sin prisas y pláticas apasionadas en vivo.',
    schedule: 'Lunes a Viernes: 19:00 - 01:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Brindis de Vino', tokens: 20, description: 'Salud a tu nombre', actionType: 'custom' },
      { id: 't2', label: 'Lovense Intensidad 8', tokens: 80, description: 'Vibración de 30 segundos', actionType: 'lovense' },
      { id: 't3', label: 'Quitar Medias de Seda', tokens: 150, description: 'Desvestido lento', actionType: 'strip' }
    ],
    chatUrl: 'https://stripcash.com/live/elena_milf',
    affiliateUrl: 'https://stripcash.com/api/models/elena_milf?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/elena_milf'
  },
  {
    id: 'm7',
    username: 'mia_vr_experience',
    displayName: 'Mia CyberVR',
    age: 23,
    country: 'Japón',
    countryCode: 'JP',
    gender: 'female',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    viewersCount: 4200,
    rating: 5.0,
    favoriteCount: 31000,
    rank: 7,
    topic: '🥽 CAM 100% COMPATIBLE CON GAFAS VR (Realidad Virtual 180° 60FPS) ⚡',
    goalTitle: 'Modo VR Interactivo 3D',
    goalCurrent: 1890,
    goalTarget: 2000,
    tags: ['VR Cams', 'Asiática', 'Petite', 'Lovense', 'HD 1080p', 'Cosplay'],
    languages: ['Japonés', 'Inglés'],
    ethnicity: 'Asiática',
    bodyType: 'Petite',
    hairColor: 'Castaño claro',
    tokensPerMin: 100,
    isHd: true,
    isVr: true,
    isLovense: true,
    bio: 'Experiencia inmersiva en Realidad Virtual de 180 grados en calidad 4K. Siente que estás en la misma habitación conmigo.',
    schedule: 'Diario: 12:00 - 20:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Acercamiento VR', tokens: 30, description: 'Primer plano directo a la cámara 3D', actionType: 'custom' },
      { id: 't2', label: 'Lovense Max VR', tokens: 120, description: 'Respuesta háptica sincronizada', actionType: 'lovense' },
      { id: 't3', label: 'Privado VR 180°', tokens: 500, description: 'Show inmersivo personal', actionType: 'custom' }
    ],
    chatUrl: 'https://stripcash.com/live/mia_vr_experience',
    affiliateUrl: 'https://stripcash.com/api/models/mia_vr_experience?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/mia_vr_experience'
  },
  {
    id: 'm8',
    username: 'scarlett_tattoo',
    displayName: 'Scarlett Ink',
    age: 24,
    country: 'Estados Unidos',
    countryCode: 'US',
    gender: 'female',
    status: 'online',
    avatarUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=400',
    snapshotUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    viewersCount: 1650,
    rating: 4.8,
    favoriteCount: 11200,
    rank: 8,
    topic: '🖤 Rock & Alt Girl | Tatuajes, piercings y música en vivo | Tip me!',
    goalTitle: 'Mostrar nuevo tatuaje oculto',
    goalCurrent: 410,
    goalTarget: 500,
    tags: ['Tatuajes', 'Piercing', 'Gótica', 'Lovense', 'HD 1080p', 'Caucásica'],
    languages: ['Inglés'],
    ethnicity: 'Caucásica',
    bodyType: 'Delgada / Tatuada',
    hairColor: 'Pelirroja',
    tokensPerMin: 55,
    isHd: true,
    isVr: false,
    isLovense: true,
    bio: 'Modelo alternativa de Los Ángeles. Fan del heavy metal, arte corporal y conversaciones atrevidas sin tabúes.',
    schedule: 'Jueves a Lunes: 01:00 - 09:00 UTC',
    galleryImages: [
      'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=600'
    ],
    tipMenu: [
      { id: 't1', label: 'Mostrar Tatuaje Secreto', tokens: 25, description: 'Muestra detalle en zoom', actionType: 'flash' },
      { id: 't2', label: 'Lovense Rock Vibe', tokens: 70, description: 'Vibración pesada por 30s', actionType: 'lovense' },
      { id: 't3', label: 'Show Toppless Alt', tokens: 220, description: 'Desnudo de torso superior', actionType: 'strip' }
    ],
    chatUrl: 'https://stripcash.com/live/scarlett_tattoo',
    affiliateUrl: 'https://stripcash.com/api/models/scarlett_tattoo?aff=12345',
    iframeEmbedUrl: 'https://stripchat.com/embed/scarlett_tattoo'
  }
];

export const INITIAL_CHAT_MESSAGES = [
  { id: 'c1', sender: 'Carlos_99', message: '¡Hola hermosa Sophia! Saludos desde México 🇲🇽', timestamp: '20:58', badge: 'FAN' as const },
  { id: 'c2', sender: 'VIP_Donator', message: 'Enviando 100 tokens para hacer vibrar el juguete! ⚡', timestamp: '20:58', isTip: true, tipAmount: 100, badge: 'TOP_TIPPER' as const },
  { id: 'c3', sender: 'Sophia Latina', message: '¡Awww gracias mi vida VIP_Donator! Siento la vibración riquísimo 😍🔥', timestamp: '20:59', isModel: true },
  { id: 'c4', sender: 'Alex_Madrid', message: '¿A cuántos tokens está el baile privado?', timestamp: '20:59', badge: 'VIP' as const },
  { id: 'c5', sender: 'Mod_Juan', message: 'Recuerden respetar las reglas del chat. ¡Disfruten el show en vivo!', timestamp: '20:59', badge: 'MOD' as const },
];
